# Main
START_NEW_USER = "START_NEW_USER\n{bot_name}\n{full_name}"
START_EXISTED_USER = "START_EXISTED_USER\n{bot_name}\n{full_name}"
BACK_MAIN_MENU = "BACK_MAIN_MENU"

# New Students
FRESHMAN_MENU = "FRESHMAN_MENU"
FRESHMAN_REGISTER = "FRESHMAN_REGISTER"

# Place
PLACE = "PLACE"
